name: ficoro_gnss
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.4
  - pandas>=3.0
  - scipy>=1.17
  - matplotlib>=3.10
  - pygmt>=0.18
  - geopy>=2.4
  - ipykernel
